### ISSUE TITLE
Vocab

### ISSUE THREAD

**Issue by AugustusHsu** [hwang1996/ACME#2]
Hi, I'm the beginner of the Recipe1M.
And I have some question about Vocabulary.
I find the `vocab.txt`, `vocab.bin`, `new_word_dict.pkl` in [arg.py](https://github.com/hwang1996/ACME/blob/master/args.py) and `ingredient_vocab.pkl` in [build_vocab.py](https://github.com/hwang1996/ACME/blob/master/build_vocab.py).

The question is :
1. For your code, I didn't see the `vocab.txt` using in anywhere. 
Also can't find this file in your GitHub. 
Is it same as the `vocab.bin`?

2. For the `new_word_dict.pkl`, I don't know how to generate this file.
And for the `ingredient_vocab.pkl`, I didn't find where you use in the code.
Are they the same?

3. I check the [im2recipe-Pytorch](https://github.com/torralba-lab/im2recipe-Pytorch).
I find the ingredient of your `[partition]_split.pkl` and the ingredient of [im2recipe-Pytorch](https://github.com/torralba-lab/im2recipe-Pytorch) is different.
Also, `vocab.bin` are different -> the index of ingredient in `vocab.bin` are different.
**In your code, you use the LMDB file in [im2recipe-Pytorch](https://github.com/torralba-lab/im2recipe-Pytorch).**
**Could the vector of the ingredient assign the wrong vector.**

4. For`ingr_cap` in  [data_loader.py](https://github.com/hwang1996/ACME/blob/318091b145d0565b52332407200043ce2132d160/data_loader.py#L102), it seem to only append the `vocab('<start>')`.
But in the [same file ](https://github.com/hwang1996/ACME/blob/318091b145d0565b52332407200043ce2132d160/data_loader.py#L149), you use it to get the `targets` (the index in the`vocab` of the ingredient )
Isn't it only have the index of the '\<start\>'?

Sorry for many problems.
And thank you for reading.

**Comment by hwang1996** [comment]
Hi,

1. They are not the same.

2. They are the same, I generated it by [build_vocab.py](https://github.com/hwang1996/ACME/blob/318091b145d0565b52332407200043ce2132d160/build_vocab.py).

3. I found there are some recipe_id mismatch between `train_lmdb` and `train_keys` in [im2recipe-Pytorch](https://github.com/torralba-lab/im2recipe-Pytorch), so I generated `[partition]_split.pkl` from `train_lmdb` again. 
As for `vocab`, I used the LMDB file to construct the recipe embeddings. There should be no issues.

4. `ingr_cap` is only for debug, actually I did not use it in training.
