### ISSUE TITLE
About the torchwordemb

### ISSUE THREAD

**Issue by scoobym** [hwang1996/ACME#4]
Hi, I just install the pytorch=0.4.1, and run `python test.py`, but find torchwordemb hasn't been installed, so I sun`pip install torchwordemb` but find `Could not find suitable distribution for Requirement.parse('torch>=1.0.0')`, can you tell me how to configure the environment?

**Comment by scoobym** [comment]
I solved this problem by installing an older version of the torchwordemb(0.0.8). 
Another question, how many cards did you use in training? How long did it take?

**Comment by hwang1996** [comment]
Hi, I trained the model with one V100 card, taking about 40 epochs/ 20 hours to finish the training.
